### ISSUE TITLE
返回类型支持jsp或者html么？

### ISSUE THREAD

**Issue by zeroleavebaoyang** [bay1ts/Bay#1]
返回类型支持指向或者跳转jsp或者html么？ 而不是java代码中去拼html代码，然后用流写

**Comment by bay1ts** [comment]
你好.暂时还不支持这个功能.但是服务器可以访问静态资源.html是可以的.暂时不支持spring mvc的那种,返回一个字符串,然后指向该jsp文件.

**Comment by bay1ts** [comment]
@zeroleavebaoyang 明天上一版 支持velocity的
